Repository NGEET/fates, pull requests merged in 2021-11, with the labels that each got.

#807 Adding distubance rate tracking and radiation profile diagnostic to initialization
  biogeochem/EDPatchDynamicsMod.F90
  main/EDInitMod.F90
Labels: bug - software engineering, High Priority, ctsm

#737 Adding the van Genuchten formula for plant P-V and P-K curves
  biogeophys/FatesHydroWTFMod.F90
  biogeophys/FatesPlantHydraulicsMod.F90
  main/EDPftvarcon.F90
  parameter_files/fates_params_default.cdl
Labels: tag: next

#750 Stem area index AND canopy snow radiation fixes.
  biogeochem/EDPatchDynamicsMod.F90
  biogeophys/EDSurfaceAlbedoMod.F90
  main/EDTypesMod.F90
  main/FatesHistoryInterfaceMod.F90
  main/FatesInterfaceMod.F90
  main/FatesInterfaceTypesMod.F90
  main/FatesRestartInterfaceMod.F90
Labels: bug - science, tag: next, ctsm

#802 Overhaul of FATES history variable outputs
  main/EDMainMod.F90
  main/FatesConstantsMod.F90
  main/FatesHistoryInterfaceMod.F90
Labels: ctsm
