Repository NGEET/fates, pull requests merged in 2022-03, with the labels that each got.

#838 Satellite phenology mode fixes for the gnu compiler
  biogeochem/EDCohortDynamicsMod.F90
  biogeochem/EDPhysiologyMod.F90
  main/EDInitMod.F90
Labels: bug - software engineering

#842 bugfix - cohort pointers and termination
  biogeochem/EDCanopyStructureMod.F90
Labels: bug - software engineering, High Priority

#831 Update FATES PFT optical to Majasalmi Bright 2019
  parameter_files/fates_params_default.cdl
Labels: ctsm
