Repository NGEET/fates, pull requests merged in 2022-06, with the labels that each got.

#877 Fix the calculation to `FATES_TVEG` to avoid crashing in debug mode with fates sp runs
  main/FatesHistoryInterfaceMod.F90
Labels: bug - software engineering

#862 parameter file updates
  biogeochem/EDCanopyStructureMod.F90
  biogeochem/EDCohortDynamicsMod.F90
  biogeochem/EDPatchDynamicsMod.F90
  biogeochem/EDPhysiologyMod.F90
  biogeochem/FatesAllometryMod.F90
  biogeophys/EDSurfaceAlbedoMod.F90
  biogeophys/FatesPlantHydraulicsMod.F90
  biogeophys/FatesPlantRespPhotosynthMod.F90
  fire/SFParamsMod.F90
  main/EDInitMod.F90
  main/EDParamsMod.F90
  main/EDPftvarcon.F90
  main/EDTypesMod.F90
  main/FatesHydraulicsMemMod.F90
  main/FatesIODimensionsMod.F90
  main/FatesIOVariableKindMod.F90
  main/FatesInterfaceMod.F90
  main/FatesInterfaceTypesMod.F90
  main/FatesInventoryInitMod.F90
  main/FatesParametersInterface.F90
  parameter_files/apichange_23to24.xml
  parameter_files/fates_params_default.cdl
  parteh/PRTAllometricCNPMod.F90
  parteh/PRTLossFluxesMod.F90
  parteh/PRTParametersMod.F90
  parteh/PRTParamsFATESMod.F90
  tools/FatesPFTIndexSwapper.py
  tools/UpdateParamAPI.py
  tools/ncvarsort.py
Labels: parameter file

#825 Pass Harvested C from FATES to ELM
  biogeochem/EDCanopyStructureMod.F90
  biogeochem/EDLoggingMortalityMod.F90
  biogeochem/EDPatchDynamicsMod.F90
  main/EDInitMod.F90
  main/EDParamsMod.F90
  main/EDTypesMod.F90
  main/FatesHistoryInterfaceMod.F90
  main/FatesInterfaceMod.F90
  main/FatesInterfaceTypesMod.F90
  main/FatesRestartInterfaceMod.F90
Labels: e3sm
