Repository NGEET/fates, pull requests merged in 2025-01, with the labels that each got.

#1303 Fix cmake breaking on functional tests for latest CTSM tag
  CMakeLists.txt
Labels: testing

#1269 handle case where LAI+SAI exceeds array by clipping instead of crashing
  biogeochem/EDCanopyStructureMod.F90
  biogeochem/EDCohortDynamicsMod.F90
  biogeochem/EDPhysiologyMod.F90
  biogeochem/FatesAllometryMod.F90
  biogeochem/FatesCohortMod.F90
  main/EDMainMod.F90
  main/FatesConstantsMod.F90
  main/FatesInterfaceMod.F90
  main/FatesParameterDerivedMod.F90
Labels: bug - software engineering

#1309 Add calculation of FATES_SAPFLOW to history interface, add sapwood area as history variable
  main/FatesHistoryInterfaceMod.F90
Labels: history output

#1273 Land Use Fixes
  biogeochem/EDLoggingMortalityMod.F90
  biogeochem/EDMortalityFunctionsMod.F90
  biogeochem/EDPatchDynamicsMod.F90
  biogeochem/FatesLandUseChangeMod.F90
  main/EDMainMod.F90
  main/FatesHistoryInterfaceMod.F90
Labels: bug - science
