Repository NGEET/fates, pull requests merged in 2025-03, with the labels that each got.

#1348 Update GetNutrientTargetCNP for Deciduous PFT
  parteh/PRTAllometricCNPMod.F90
Labels: science: bug, software: bug, science: nutrients, PFT: deciduous

#1339 bugfix on harvesting of unoccupied canopy area
  biogeochem/EDPatchDynamicsMod.F90
Labels: software: bug, science: harvesting

#1321 restart fixes for two-stream
  biogeochem/EDCanopyStructureMod.F90
  biogeochem/EDPatchDynamicsMod.F90
  biogeochem/FatesPatchMod.F90
  biogeophys/FatesPlantRespPhotosynthMod.F90
  main/EDInitMod.F90
  main/EDTypesMod.F90
  main/FatesInterfaceMod.F90
  main/FatesInterfaceTypesMod.F90
  main/FatesRestartInterfaceMod.F90
  radiation/FatesNormanRadMod.F90
  radiation/FatesRadiationDriveMod.F90
  radiation/FatesTwoStreamUtilsMod.F90
  radiation/TwoStreamMLPEMod.F90
Labels: science: radiation, case: restart
